###########
# site.title

title:    'Nik Korablin'
subtitle: 'I like pizza, unit tests, and freedom'
bio: >
  I am fullstack Javascript developer, classically trained in Java. I studied Computer Science at
  <a target="_blank" href="http://temple.edu">Temple University</a> in Philadelphia. I formally worked at <a target="_blank" href="http://vanguard.com">Vanguard</a> and currently
  working on a <a target="_blank" href="http://whoseyourlandlord.com">couple</a> <a target="_blank" href="http://godelsystem.com">different</a> projects. I live in Lancaster, PA with my wife. I am the youth group leader at my
  church. When I am away from my computer, I enjoy driving, cooking, and being outside. Email me at <a href="mailto:nikorablin@gmail.com">nikorablin@gmail.com</a>

nav:
  - { title: 'Github',  href: 'http://github.com/nikorablin' }
  - { title: 'CV',      href: '/cv' }
  - { title: 'Twitter', href: 'http://twitter.com/nikorablin' }

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md
